title: "Monsti CMS Example Site"
hosts: ["localhost:8080"]
locale: en
# Name and email address of site owner.
#
# The owner's address is used as recipient of contact form submissions.
owner:
  name: The Owner
  email: owner@example.com
# Key used for signing session cookie data. Change this!
sessionauthkey: aoeuiaoeuiaoeuiaoeuiaoeuiaoeuiaoaoeuiaoeuiaoeuiaoeuiaoeuiaoeuiao
