title: "Monsti CMS Example Site"
hosts: ["localhost:8080"]
baseurl: "http://localhost:8080"
locale: en

# Name and address as used in mails composed by Monsti, e.g. password
# change mails.
emailname: "Example site"
emailaddress: "noreply@localhost"

# The site's time zone as defined in the IANA Time Zone database.
timezone: "Europe/Berlin"

# Name and email address of site owner.
#
# The owner's address is used as recipient of contact form submissions.
owner:
  name: The Owner
  email: owner@example.com

# Key used for signing session cookie data. Change this!
sessionauthkey: aoeuiaoeuiaoeuiaoeuiaoeuiaoeuiaoaoeuiaoeuiaoeuiaoeuiaoeuiaoeuiao
# Key used for signing password request tokens. Change this!
passwordtokenkey: foobarblacruz
