# SMTP settings for outgoing mail
#mail:
#  host: localhost
#  username: user
#  password: password

# Enabled node types
nodetypes: [Document, Image, ContactForm]

# Listen for HTTP connections on this address and port
listen: localhost:8080

directories:
  # Path to the static files.
  statics: ../../static
  # Path to the template directory.
  templates: ../../templates
  locales: ../../locale
