# Main configuration used by all modules.

# Common directories. Specify absolute or configuration directory relative paths.
directories:
  # Files used by all sites like Monsti's default templates, locales, and
  # static web files.
  shared: ../shared
  # Site specific data like node content, stylesheets, and custom templates.
  data: ../data
  # Run time data like process ids or socket files.
  run: ../run
