# This file is part of Monsti, a web content management system.
# Copyright 2012-2014 Christian Neumann
#
# Monsti is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Monsti is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Monsti.  If not, see <http:#www.gnu.org/licenses/>.

namespace: core
nodetypes:
  - id: FieldsExample
    addable_to: []
    name: {en: "Fields Example", de: "Felder-Beispiel"}
    fields:
      - id: Title
        name: {en: "Title", de: "Titel"}
        type: Text
      - id: HTMLArea
        name: {en: "HTMLArea", de: "HTMLArea"}
        type: HTMLArea
      - id: Text
        name: {en: "Text", de: "Text"}
        type: Text
      - id: DateTime
        name: {en: "DateTime", de: "DateTime"}
        type: DateTime